"""add background job

Revision ID: c7f9e8a1d2b3
Revises: 94b8e23f11a4
Create Date: 2026-07-22 10:37:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7f9e8a1d2b3"
down_revision: Union[str, None] = "94b8e23f11a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # type: ignore
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # type: ignore
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("execute_after", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_background_jobs_execute_after"),
        "background_jobs",
        ["execute_after"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_jobs_organization_id"),
        "background_jobs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_jobs_status"), "background_jobs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_background_jobs_task_name"),
        "background_jobs",
        ["task_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_background_jobs_task_name"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_status"), table_name="background_jobs")
    op.drop_index(
        op.f("ix_background_jobs_organization_id"), table_name="background_jobs"
    )
    op.drop_index(
        op.f("ix_background_jobs_execute_after"), table_name="background_jobs"
    )
    op.drop_table("background_jobs")
    # ### end Alembic commands ###
