"""add webhook event

Revision ID: d8e1f3a9b2c4
Revises: c7f9e8a1d2b3
Create Date: 2026-07-22 10:43:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d8e1f3a9b2c4"
down_revision: Union[str, None] = "c7f9e8a1d2b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),  # type: ignore
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # type: ignore
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_provider_event_id"
        ),
    )
    op.create_index(
        op.f("ix_webhook_events_event_type"),
        "webhook_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_events_provider"), "webhook_events", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_events_provider_event_id"),
        "webhook_events",
        ["provider_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_events_status"), "webhook_events", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_events_status"), table_name="webhook_events")
    op.drop_index(
        op.f("ix_webhook_events_provider_event_id"), table_name="webhook_events"
    )
    op.drop_index(op.f("ix_webhook_events_provider"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_type"), table_name="webhook_events")
    op.drop_table("webhook_events")
    # ### end Alembic commands ###
