"""add notification log

Revision ID: e9f2a4b6c8d0
Revises: d8e1f3a9b2c4
Create Date: 2026-07-22 10:50:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9f2a4b6c8d0"
down_revision: Union[str, None] = "d8e1f3a9b2c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("template_name", sa.String(length=100), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # type: ignore
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("provider_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),  # type: ignore
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_logs_channel"),
        "notification_logs",
        ["channel"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_organization_id"),
        "notification_logs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_recipient"),
        "notification_logs",
        ["recipient"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_logs_status"),
        "notification_logs",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_logs_status"), table_name="notification_logs")
    op.drop_index(
        op.f("ix_notification_logs_recipient"), table_name="notification_logs"
    )
    op.drop_index(
        op.f("ix_notification_logs_organization_id"), table_name="notification_logs"
    )
    op.drop_index(op.f("ix_notification_logs_channel"), table_name="notification_logs")
    op.drop_table("notification_logs")
    # ### end Alembic commands ###
